### ISSUE TITLE
Unable to start, exit status 9

### ISSUE THREAD

**Issue by zbacsi** [magland/theiapod#2]
This is a fresh install of Ubuntu 18.04. 
Git, docker, Python3 installed.

```
# theiapod https://github.com/magland/theiapod --port 3000
RUNNING: git clone https://github.com/magland/theiapod /tmp/theiapod_workspace_OYQJ9Y05SM
Cloning into '/tmp/theiapod_workspace_OYQJ9Y05SM'...
remote: Enumerating objects: 147, done.
remote: Total 147 (delta 0), reused 0 (delta 0), pack-reused 147
Receiving objects: 100% (147/147), 25.79 KiB | 1.03 MiB/s, done.
Resolving deltas: 100% (68/68), done.
:::::::::::::::::::::::config: {}
Using image: magland/theiapod:latest
RUNNING: docker pull magland/theiapod:latest
latest: Pulling from magland/theiapod
Digest: sha256:b9ba52ddbbca19cdbc5c15bf2da32f664920fa884d6f7e6665f8d99ffdffabe2
Status: Image is up to date for magland/theiapod:latest
RUNNING: docker run -p 3000:3000 -it -v /usr/local/lib/python3.6/dist-packages/theiapod/theiapod_init_in_container.py:/theiapod_init -v /tmp/theiapod_workspace_OYQJ9Y05SM:/home/project --network host -v /tmp:/tmp  magland/theiapod:latest /home/project 3000 root 0
WARNING: Published ports are discarded when using host network mode
+ PROJECT_DIRECTORY=/home/project
+ PORT=3000
+ USER=root
+ UID_=0
+ useradd -l -u 0 -G sudo -md /home/root -s /bin/bash -p root root
useradd: user 'root' already exists
Traceback (most recent call last):
  File "/usr/local/bin/theiapod", line 65, in <module>
    main()
  File "/usr/local/bin/theiapod", line 31, in main
    docker_opts=args.docker_opts
  File "/usr/local/lib/python3.6/dist-packages/theiapod/impl.py", line 101, in theiapod
    _run_command_and_print_output(cmd)
  File "/usr/local/lib/python3.6/dist-packages/theiapod/impl.py", line 137, in _run_command_and_print_output
    execute(cmd.split())
  File "/usr/local/lib/python3.6/dist-packages/theiapod/impl.py", line 133, in execute
    raise subprocess.CalledProcessError(return_code, cmd)
subprocess.CalledProcessError: Command '['docker', 'run', '-p', '3000:3000', '-it', '-v', '/usr/local/lib/python3.6/dist-packages/theiapod/theiapod_init_in_container.py:/theiapod_init', '-v', '/tmp/theiapod_workspace_OYQJ9Y05SM:/home/project', '--network', 'host', '-v', '/tmp:/tmp', 'magland/theiapod:latest', '/home/project', '3000', 'root', '0']' returned non-zero exit status 9.
```

What could be the problem?

**Comment by nerodark** [comment]
You are running theiapod as root, you have to run it as a regular user with docker access.
Add your regular user to the docker group : usermod -aG docker YOUR-USER-HERE
Logout and log back in, now you can start theiapod (don't start it with sudo)
