### ISSUE TITLE
SyntaxError: invalid syntax (def theiapod)

### ISSUE THREAD

**Issue by samos667** [magland/theiapod#3]
root@k8s1:~# theiapod https://github.com/magland/theiapod --port 3000
Traceback (most recent call last):
  File "/usr/local/bin/theiapod", line 4, in <module>
    import theiapod as tp
  File "/usr/local/lib/python2.7/dist-packages/theiapod/__init__.py", line 1, in <module>
    from .impl import theiapod
  File "/usr/local/lib/python2.7/dist-packages/theiapod/impl.py", line 11
    def theiapod(*,repository='',port=3000,image=None,expose_ports=[],volumes=[],mount_tmp=True,host_working_directory=None,docker_opts=None):
                  ^
SyntaxError: invalid syntax

**Comment by Atem18** [comment]
@samos667 you installed that module with python2, it had been written with Python3 as you can see here : https://github.com/magland/theiapod/blob/master/setup.py
